In [4]:
import numpy as np

In [6]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [8]:
b = np.array([[1,2,3],[3,4,5]])
print(b)

[[1 2 3]
 [3 4 5]]


In [12]:
# Get Dimension
b.ndim

2

In [13]:
# Get Shape
b.shape 

(2, 3)